// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WestCoastEducation2.web.Data;



#nullable disable

namespace WestCoastEducation2.web.Data.Migrations
{
    [DbContext(typeof(westcoasteducationContext))]
    [Migration("20230105132112_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.1");
modelBuilder.Entity("WestCoastEducation2.web.Models.Courses", b => 
{
    b.Property<string>("name")
        .IsRequired()
        .HasColumnType("TEXT");
    b.Property<string>("courseNumber")
        .IsRequired()
        .HasColumnType("TEXT");
        b.Property<string>("teacher")
        .IsRequired()
        .HasColumnType("TEXT");
        b.Property<string>("placeStudy")
        .IsRequired()
        .HasColumnType("TEXT");
        b.Property<DateTime >("startDate")
        .IsRequired()
        .HasColumnType("Date");
        b.Property<DateTime >("endDate")
        .IsRequired()
        .HasColumnType("Date");
        b.ToTable("Courses");
});
#pragma warning restore 612, 618
        }
    }
}
